description = "Generate a high-quality technical design with approval workflow and interactive discussion. Usage: /command <feature_name>"

prompt = """
The user wants to generate the design for '{{feature_name}}'.

**Step 1: Read Workflow Configuration**
- Read the file `.kiro/config.json` to determine `approval_mode`.

**Step 1.5: Read Language Setting**
- Read `language` from `.kiro/specs/{{feature_name}}/spec.json`.
- If not found, read from `.kiro/config.json`.
- If still not found, default to English.
- Store this language for all user-facing messages in this run.
- If spec.json file doesn't exist, default to `implicit` approval mode.

**Step 2: Conditional Approval for Requirements**
- **IF `approval_mode` is `interactive`**:
  1. Use the following English template and translate it before showing:
     "Have you reviewed and approved the requirements.md for '{{feature_name}}'? [y/N]"
  2. If user answers 'y' or 'yes', continue; else stop and instruct user to review the requirements.
- **ELSE** (approval_mode is `implicit` or unset):
  1. Proceed without confirmation.

**Step 3: Approve Requirements & Initiate Design Discussion**

1. Update `.kiro/specs/{{feature_name}}/spec.json`:
   - Set `requirements.approved` to true and `phase` to "requirements-approved".
2. Read `.kiro/specs/{{feature_name}}/requirements.md`.
3. Read steering docs: `@.kiro/steering/product.md`, `@.kiro/steering/tech.md`, `@.kiro/steering/structure.md`.
4. Read existing `.kiro/specs/{{feature_name}}/design.md` if exists.
5. Identify key technical decisions from above.

**Step 3.1: MANDATORY RESEARCH PHASE**

- You MUST perform a web search **before** proposing any technical solutions.
- Formulate a concise search query based on the key technical decisions identified.
- Display the following English template prompt (translated to the resolved language) exactly as:  
  "Searching for: '<QUERY>'"
- Immediately and unconditionally call the `google_web_search` tool with the formulated query.  
  **DO NOT wait for user input or confirmation.**
- Use the search results from `google_web_search` directly to inform your proposed technical approaches.
- For each key decision, propose 2-3 viable technical approaches.
- For each approach, provide a detailed explanation of its pros and cons.
- Use bullet points for clarity.
  
### User Discussion Phase

- Present the technical approaches with pros and cons clearly.
- Do NOT generate the full design until user provides feedback.
- Prompt the user explicitly to provide their preferred approach or further comments.

**Step 4: Generate Final Technical Design**

1. Incorporate user feedback to finalize approaches.
2. Generate and overwrite `.kiro/steering/tech.md` with final tech stack.
3. Generate comprehensive design document including:
   - Architecture overview
   - Data flow diagram (Mermaid.js format)
   - Component breakdown
   - Data schema / ERD
   - Security considerations
   - Testing strategy
4. Write design to `.kiro/specs/{{feature_name}}/design.md`.
5. Update `.kiro/specs/{{feature_name}}/spec.json`:
   - Set `design.generated` to true and `phase` to "design-generated".

**Step 5: Completion Notification**

- Use English template translated to resolved language:
  "Design document and tech stack updated. Please review and then run `/spec:tasks {{feature_name}}` to proceed."
"""

allowed_tools = ["read_file", "write_file", "google_web_search", "list_directory"]
