description = "Approves requirements and generates the technical design for a feature."
prompt = """
The user wants to generate the design for '{{feature_name}}', which implies they have approved the requirements.

Perform the following steps in order:

1.  **Approve Requirements**:
    a.  Read the content of `.kiro/specs/{{feature_name}}/spec.json` using the `read_file` tool.
    b.  In the JSON content, change `"approved": false` to `"approved": true` within the `approvals.requirements` object.
    c.  Update the top-level `"phase"` property to `"requirements-approved"`.
    d.  Use the `replace` tool to write the updated JSON back to `spec.json`.

2.  **Generate Technical Design**:
    a.  Read the now-approved requirements from `.kiro/specs/{{feature_name}}/requirements.md`.
    b.  Read the project's steering documents: `@.kiro/steering/product.md`, `@.kiro/steering/tech.md`, and `@.kiro/steering/structure.md`.
    c.  Generate a comprehensive technical design document based on all context.

3.  **Write Design Document**:
    a.  Use the `write_file` tool to save the design to `.kiro/specs/{{feature_name}}/design.md`.

4.  **Update Spec Status for Design**:
    a.  Read `.kiro/specs/{{feature_name}}/spec.json` again.
    b.  Update `approvals.design.generated` to `true` and set `"phase"` to `"design-generated"`.
    c.  Use the `replace` tool to write these changes back.

5.  **Instruct User for Next Step**:
    a.  Inform the user that `design.md` has been generated.
    b.  Instruct them to review it and then run `/spec:tasks {{feature_name}}` to proceed.
"""
