description = "Approves the design and generates implementation tasks for a feature."
prompt = """
The user wants to generate tasks for '{{feature_name}}', which implies they have approved the design.

Perform the following steps in order:

1.  **Approve Design**:
    a.  Read the content of `.kiro/specs/{{feature_name}}/spec.json` using the `read_file` tool.
    b.  In the JSON content, change `"approved": false` to `"approved": true` within the `approvals.design` object.
    c.  Update the top-level `"phase"` property to `"design-approved"`.
    d.  Use the `replace` tool to write the updated JSON back to `spec.json`.

2.  **Generate Implementation Tasks**:
    a.  Read the approved technical design from `.kiro/specs/{{feature_name}}/design.md`.
    b.  Break down the design into a detailed list of actionable implementation tasks with Markdown checkboxes.

3.  **Write Tasks Document**:
    a.  Use the `write_file` tool to save the tasks to `.kiro/specs/{{feature_name}}/tasks.md`.

4.  **Update Spec Status for Tasks**:
    a.  Read `.kiro/specs/{{feature_name}}/spec.json` again.
    b.  Update `approvals.tasks.generated` to `true` and set `"phase"` to `"tasks-generated"`.
    c.  Use the `replace` tool to write these changes back.

5.  **Instruct User for Next Step**:
    a.  Inform the user that `tasks.md` has been generated and reviewed.
    b.  State that the feature is now ready for implementation.
"""
